name: 自动续时蓝天云

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *' # 每天一次，UTC 时间晚上 10 点运行（即北京时间早上 6 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 从文件读取需要续费的ID
      run: |
          sudo apt-get update && sudo apt-get install -y jq
           curl -fsSL git.io/warp.sh -o warp.sh
          sudo bash warp.sh 4
          curl -s https://lantian.pro/
